name: Smoketest

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    name: Format and build

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Prettier
        run: |
          yarn global add prettier @prettier/plugin-php
          echo "$(yarn global bin)" >> $GITHUB_PATH

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2

      - name: Verify formatting
        run: composer run format:check

      - uses: flarum/action-build@2
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: yarn
